name = "abc"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Abc"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "Canonical"
scope = "chasenorman"

[[lean_lib]]
name = "Abc"
